### ISSUE TITLE
 I downloaded it  aixtools.python.2.7.12.3.I , How should this be used?

### ISSUE THREAD

**Issue by zixiliuyue** [kairoaraujo/Python-AIX-RPM#2]
I used AIX for the first time,puzzled ,search does not know what keywords should be used. Do you have any suggestions, thank you?

**Comment by kairoaraujo** [comment]
Hi, it is a AIX package. You can install it using smitty install

**Comment by zixiliuyue** [comment]
Thank you, I've complete. Finally I build the Python 2.7.12 package for AIX 5,AIX 6,aix7. Over a period of time, I also shared it.
